language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install python-coveralls
  - pip install coverage
  - cd python/
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
after_success:
  - coveralls
