language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install coveralls
  - cd python/
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
  - pep8
after_success:
  - coveralls
